
server.port: 9090
spring:
  application:
    name: spring-boot-admin-client




info:
  tags:
    environment: test

#配置Eureka客户端
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/


#通过http暴露所有的endpoints(spring boot 2 大部门都没有暴露)
management:
  endpoints:
    web:
      exposure:
        include: "*"
        endpoint:
          health:
            show-details: ALWAYS